### PR TITLE
Created document outlining which files metadata may be extracted from

### LINKED ISSUE #106: Metadata command: Create a list of use-cases
- [ ] Create a list of use-cases / variants for the files we're going to process
    - [ ] Create a list of vendors
    - [ ] Create a list of support files each vendor produces that we could extract metadata from (logs, configuration files, schedules, other data files, etc...)

### PR DESCRIPTION
**Pull request by noahmacaskill**
Our findings on some of the files we can hopefully extract metadata from.

Closes #106

### CODE REVIEW

**Review by atruskie — CHANGES_REQUESTED** [review]
Use _camelCase_ for naming the files please. (`Metadata.md` --> `metadata.md`).

This is a good start. 

- Missing vendors: 
   - Swift ?
- Missing sensors:
   - SM2 ?
   - SM3 ?
   - BAR

There are going to be 4 categories of metadata we can extract:
- file name
- file header
- data files
- other files

So can we set up a structure as so:

```
## <Vendor>

### <Sensor>

| Name                | Supported | Location(s)  | Notes    |
|---------------------|-----------|--------------|----------|
| Recorded start date | ✅         | File name    |          |
| Battery level       | ❌         | header       |          |
| Temperature         | ❌         | data file    |          |
| SD Card health      | ❌         | support file | log file |
```

The idea here is once we have support for each feature, we'll swap out the supported emoji for a tick. 

I'll also assign each of you work based on what we have left to do.

**Comment by noahmacaskill** [comment]
Still a work in progress. Will see what else we can dig up next week, and will have a look at those missing sensors as well to see what we can find.

**Comment by atruskie** [comment]
@noahmacaskill you don't have to completely fill in the table, especially for sensors you're not interested in. But if we have some placeholders we can't hint to people that we (or I) would at least be keen to add support for other things as well even if it is not on our hot path now.

**Comment by atruskie** [comment]
Ok this looks great!

We can always extend this later when we find new bits of metadata. 

It's still a draft PR, are you happy with it enough to merge it @noahmacaskill @JordanMercerECCC ?

**Comment by noahmacaskill** [comment]
We're good to merge. I have it placed it in the docs/ directory, that make sense?

**Pull request merged**
